From 49052dd010637e1403c8b2b1c3710926acd2b1a0 Mon Sep 17 00:00:00 2001
From: Grokzen <Grokzen@gmail.com>
Date: Wed, 9 Oct 2019 23:21:09 +0200
Subject: [PATCH] Fixed bug in test_multi_file_support where pytest would raise
 issue with a option that is no longer supported

---
 tests/test_core.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/tests/test_core.py b/tests/test_core.py
index 6fcd81e..bd974df 100644
--- a/tests/test_core.py
+++ b/tests/test_core.py
@@ -336,7 +336,9 @@ def test_multi_file_support(self):
             compare(c.root_rule.schema_str, passing_test[2], prefix="Parsed rules is not correct, something have changed...")
 
         for failing_test in failing_tests:
-            with pytest.raises(failing_test[2], message="Test files: {0} : {1}".format(", ".join(failing_test[0]), failing_test[1])):
+            print("Test files: {0} : {1}".format(", ".join(failing_test[0]), failing_test[1]))
+
+            with pytest.raises(failing_test[2]):
                 c = Core(schema_files=failing_test[0], source_file=failing_test[1])
                 c.validate()
 
